package com.gz.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_ad", "id", Ad.class);
		arp.addMapping("tb_attachment", "id", Attachment.class);
		arp.addMapping("tb_attribute", "id", Attribute.class);
		arp.addMapping("tb_attribute_value", "id", AttributeValue.class);
		arp.addMapping("tb_category", "id", Category.class);
		arp.addMapping("tb_content", "id", Content.class);
		arp.addMapping("tb_content_attachment", "id", ContentAttachment.class);
		arp.addMapping("tb_coupon", "id", Coupon.class);
		arp.addMapping("tb_field", "id", Field.class);
		arp.addMapping("tb_lanmu", "id", Lanmu.class);
		arp.addMapping("tb_product", "id", Product.class);
		arp.addMapping("tb_product_attachment", "id", ProductAttachment.class);
		arp.addMapping("tb_product_attribute", "id", ProductAttribute.class);
		arp.addMapping("tb_product_attribute_value", "id", ProductAttributeValue.class);
		arp.addMapping("tb_product_promotion", "id", ProductPromotion.class);
		arp.addMapping("tb_promotion", "id", Promotion.class);
		arp.addMapping("tb_role", "id", Role.class);
		arp.addMapping("tb_role_lanmu", "id", RoleLanmu.class);
		arp.addMapping("tb_user", "id", User.class);
	}
}

