package com.gz.common.model;

import com.gz.common.model.base.BaseAd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Ad extends BaseAd<Ad> {
	public static final Ad dao = new Ad().dao();
}
