package com.gz.common.model;

import com.gz.common.model.base.BaseAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attachment extends BaseAttachment<Attachment> {
	public static final Attachment dao = new Attachment().dao();
}
