package com.gz.common.model;

import com.gz.common.model.base.BaseAttributeValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AttributeValue extends BaseAttributeValue<AttributeValue> {
	public static final AttributeValue dao = new AttributeValue().dao();
}
