package com.gz.common.model;

import com.gz.common.model.base.BaseContentAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContentAttachment extends BaseContentAttachment<ContentAttachment> {
	public static final ContentAttachment dao = new ContentAttachment().dao();
}
