package com.gz.common.model;

import com.gz.common.model.base.BaseField;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Field extends BaseField<Field> {
	public static final Field dao = new Field().dao();
}
