package com.gz.common.model;

import com.gz.common.model.base.BaseLanmu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Lanmu extends BaseLanmu<Lanmu> {
	public static final Lanmu dao = new Lanmu().dao();
}
