package com.gz.common.model;

import com.gz.common.model.base.BaseProductAttributeValue;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductAttributeValue extends BaseProductAttributeValue<ProductAttributeValue> {
	public static final ProductAttributeValue dao = new ProductAttributeValue().dao();
}
