package com.gz.common.model;

import com.gz.common.model.base.BaseProductAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductAttribute extends BaseProductAttribute<ProductAttribute> {
	public static final ProductAttribute dao = new ProductAttribute().dao();
}
