package com.gz.common.model;

import com.gz.common.model.base.BaseProductAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductAttachment extends BaseProductAttachment<ProductAttachment> {
	public static final ProductAttachment dao = new ProductAttachment().dao();
}
