package com.gz.common.model;

import com.gz.common.model.base.BaseProductPromotion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductPromotion extends BaseProductPromotion<ProductPromotion> {
	public static final ProductPromotion dao = new ProductPromotion().dao();
}
