package com.gz.common.model;

import com.gz.common.model.base.BasePromotion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Promotion extends BasePromotion<Promotion> {
	public static final Promotion dao = new Promotion().dao();
}
