package com.gz.common.model;

import com.gz.common.model.base.BaseRoleLanmu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleLanmu extends BaseRoleLanmu<RoleLanmu> {
	public static final RoleLanmu dao = new RoleLanmu().dao();
}
