package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setCaption(java.lang.String caption) {
		set("caption", caption);
		return (M)this;
	}
	
	public java.lang.String getCaption() {
		return getStr("caption");
	}

	public M setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
		return (M)this;
	}
	
	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

	public M setIntroduction(java.lang.String introduction) {
		set("introduction", introduction);
		return (M)this;
	}
	
	public java.lang.String getIntroduction() {
		return getStr("introduction");
	}

	public M setProductCategoryId(java.lang.Integer productCategoryId) {
		set("productCategoryId", productCategoryId);
		return (M)this;
	}
	
	public java.lang.Integer getProductCategoryId() {
		return getInt("productCategoryId");
	}

	public M setSn(java.lang.String sn) {
		set("sn", sn);
		return (M)this;
	}
	
	public java.lang.String getSn() {
		return getStr("sn");
	}

	public M setSales(java.lang.Integer sales) {
		set("sales", sales);
		return (M)this;
	}
	
	public java.lang.Integer getSales() {
		return getInt("sales");
	}

	public M setIsMarketable(java.lang.Boolean isMarketable) {
		set("isMarketable", isMarketable);
		return (M)this;
	}
	
	public java.lang.Boolean getIsMarketable() {
		return get("isMarketable");
	}

	public M setPrice(java.lang.Float price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.Float getPrice() {
		return getFloat("price");
	}

	public M setMarketPrice(java.lang.Float marketPrice) {
		set("marketPrice", marketPrice);
		return (M)this;
	}
	
	public java.lang.Float getMarketPrice() {
		return getFloat("marketPrice");
	}

	public M setStock(java.lang.Integer stock) {
		set("stock", stock);
		return (M)this;
	}
	
	public java.lang.Integer getStock() {
		return getInt("stock");
	}

	public M setParameterValue(java.lang.String parameterValue) {
		set("parameterValue", parameterValue);
		return (M)this;
	}
	
	public java.lang.String getParameterValue() {
		return getStr("parameterValue");
	}

	public M setSortNum(java.lang.Integer sortNum) {
		set("sort_num", sortNum);
		return (M)this;
	}
	
	public java.lang.Integer getSortNum() {
		return getInt("sort_num");
	}

	public M setIsRecommend(java.lang.Integer isRecommend) {
		set("isRecommend", isRecommend);
		return (M)this;
	}
	
	public java.lang.Integer getIsRecommend() {
		return getInt("isRecommend");
	}

}
