package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCoupon<M extends BaseCoupon<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setMoney(java.lang.Integer money) {
		set("money", money);
		return (M)this;
	}
	
	public java.lang.Integer getMoney() {
		return getInt("money");
	}

	public M setLeastSpendMoney(java.lang.Integer leastSpendMoney) {
		set("leastSpendMoney", leastSpendMoney);
		return (M)this;
	}
	
	public java.lang.Integer getLeastSpendMoney() {
		return getInt("leastSpendMoney");
	}

	public M setStatus(java.lang.Boolean status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public M setPeriod(java.lang.Integer period) {
		set("period", period);
		return (M)this;
	}
	
	public java.lang.Integer getPeriod() {
		return getInt("period");
	}

	public M setPromotionId(java.lang.Integer promotionId) {
		set("promotionId", promotionId);
		return (M)this;
	}
	
	public java.lang.Integer getPromotionId() {
		return getInt("promotionId");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

}
