package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContentAttachment<M extends BaseContentAttachment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAttachmentId(java.lang.Integer attachmentId) {
		set("attachmentId", attachmentId);
		return (M)this;
	}
	
	public java.lang.Integer getAttachmentId() {
		return getInt("attachmentId");
	}

	public M setContentId(java.lang.Integer contentId) {
		set("contentId", contentId);
		return (M)this;
	}
	
	public java.lang.Integer getContentId() {
		return getInt("contentId");
	}

	public M setSortNum(java.lang.Integer sortNum) {
		set("sort_num", sortNum);
		return (M)this;
	}
	
	public java.lang.Integer getSortNum() {
		return getInt("sort_num");
	}

}
