package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProductAttributeValue<M extends BaseProductAttributeValue<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProductId(java.lang.Integer productId) {
		set("productId", productId);
		return (M)this;
	}
	
	public java.lang.Integer getProductId() {
		return getInt("productId");
	}

	public M setAttributeValues(java.lang.String attributeValues) {
		set("attributeValues", attributeValues);
		return (M)this;
	}
	
	public java.lang.String getAttributeValues() {
		return getStr("attributeValues");
	}

	public M setStock(java.lang.Integer stock) {
		set("stock", stock);
		return (M)this;
	}
	
	public java.lang.Integer getStock() {
		return getInt("stock");
	}

	public M setPrice(java.lang.Float price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.Float getPrice() {
		return getFloat("price");
	}

	public M setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
		return (M)this;
	}
	
	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

	public M setSKU(java.lang.String SKU) {
		set("SKU", SKU);
		return (M)this;
	}
	
	public java.lang.String getSKU() {
		return getStr("SKU");
	}

}
