package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseField<M extends BaseField<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setFieldZh(java.lang.String fieldZh) {
		set("field_zh", fieldZh);
		return (M)this;
	}
	
	public java.lang.String getFieldZh() {
		return getStr("field_zh");
	}

	public M setFieldEn(java.lang.String fieldEn) {
		set("field_en", fieldEn);
		return (M)this;
	}
	
	public java.lang.String getFieldEn() {
		return getStr("field_en");
	}

	public M setFieldType(java.lang.String fieldType) {
		set("field_type", fieldType);
		return (M)this;
	}
	
	public java.lang.String getFieldType() {
		return getStr("field_type");
	}

	public M setFiledLength(java.lang.Integer filedLength) {
		set("filed_length", filedLength);
		return (M)this;
	}
	
	public java.lang.Integer getFiledLength() {
		return getInt("filed_length");
	}

	public M setIsEditor(java.lang.Integer isEditor) {
		set("is_editor", isEditor);
		return (M)this;
	}
	
	public java.lang.Integer getIsEditor() {
		return getInt("is_editor");
	}

	public M setLanmuId(java.lang.Integer lanmuId) {
		set("lanmu_id", lanmuId);
		return (M)this;
	}
	
	public java.lang.Integer getLanmuId() {
		return getInt("lanmu_id");
	}

	public M setLanmuOption(java.lang.Integer lanmuOption) {
		set("lanmu_option", lanmuOption);
		return (M)this;
	}
	
	public java.lang.Integer getLanmuOption() {
		return getInt("lanmu_option");
	}

	public M setFieldShow(java.lang.Integer fieldShow) {
		set("field_show", fieldShow);
		return (M)this;
	}
	
	public java.lang.Integer getFieldShow() {
		return getInt("field_show");
	}

	public M setSortNum(java.lang.Integer sortNum) {
		set("sort_num", sortNum);
		return (M)this;
	}
	
	public java.lang.Integer getSortNum() {
		return getInt("sort_num");
	}

}
