package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePromotion<M extends BasePromotion<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setTag(java.lang.String tag) {
		set("tag", tag);
		return (M)this;
	}
	
	public java.lang.String getTag() {
		return getStr("tag");
	}

	public M setStartDate(java.util.Date startDate) {
		set("startDate", startDate);
		return (M)this;
	}
	
	public java.util.Date getStartDate() {
		return get("startDate");
	}

	public M setEndDate(java.util.Date endDate) {
		set("endDate", endDate);
		return (M)this;
	}
	
	public java.util.Date getEndDate() {
		return get("endDate");
	}

	public M setActive(java.lang.Boolean active) {
		set("active", active);
		return (M)this;
	}
	
	public java.lang.Boolean getActive() {
		return get("active");
	}

	public M setCreatDate(java.util.Date creatDate) {
		set("creatDate", creatDate);
		return (M)this;
	}
	
	public java.util.Date getCreatDate() {
		return get("creatDate");
	}

	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public M setReduceMoney(java.lang.Float reduceMoney) {
		set("reduceMoney", reduceMoney);
		return (M)this;
	}
	
	public java.lang.Float getReduceMoney() {
		return getFloat("reduceMoney");
	}

	public M setLastSpendMoney(java.lang.Float lastSpendMoney) {
		set("lastSpendMoney", lastSpendMoney);
		return (M)this;
	}
	
	public java.lang.Float getLastSpendMoney() {
		return getFloat("lastSpendMoney");
	}

}
