package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAttachment<M extends BaseAttachment<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setUserId(java.lang.Integer userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public java.lang.Integer getUserId() {
		return getInt("user_id");
	}

	public M setUrl(java.lang.String url) {
		set("url", url);
		return (M)this;
	}
	
	public java.lang.String getUrl() {
		return getStr("url");
	}

	public M setMimeType(java.lang.String mimeType) {
		set("mime_type", mimeType);
		return (M)this;
	}
	
	public java.lang.String getMimeType() {
		return getStr("mime_type");
	}

	public M setSuffix(java.lang.String suffix) {
		set("suffix", suffix);
		return (M)this;
	}
	
	public java.lang.String getSuffix() {
		return getStr("suffix");
	}

	public M setCreated(java.util.Date created) {
		set("created", created);
		return (M)this;
	}
	
	public java.util.Date getCreated() {
		return get("created");
	}

	public M setSize(java.lang.Long size) {
		set("size", size);
		return (M)this;
	}
	
	public java.lang.Long getSize() {
		return getLong("size");
	}

}
