package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProductAttribute<M extends BaseProductAttribute<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setProductId(java.lang.Integer productId) {
		set("productId", productId);
		return (M)this;
	}
	
	public java.lang.Integer getProductId() {
		return getInt("productId");
	}

	public M setAttributeValueId(java.lang.Integer attributeValueId) {
		set("attributeValueId", attributeValueId);
		return (M)this;
	}
	
	public java.lang.Integer getAttributeValueId() {
		return getInt("attributeValueId");
	}

	public M setPrice(java.lang.Integer price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.Integer getPrice() {
		return getInt("price");
	}

	public M setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
		return (M)this;
	}
	
	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

}
