package com.gz.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContent<M extends BaseContent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setColumn4(java.lang.String column4) {
		set("column4", column4);
		return (M)this;
	}
	
	public java.lang.String getColumn4() {
		return getStr("column4");
	}

	public M setColumn2(java.lang.String column2) {
		set("column2", column2);
		return (M)this;
	}
	
	public java.lang.String getColumn2() {
		return getStr("column2");
	}

	public M setColumn3(java.lang.String column3) {
		set("column3", column3);
		return (M)this;
	}
	
	public java.lang.String getColumn3() {
		return getStr("column3");
	}

	public M setColumn1(java.lang.String column1) {
		set("column1", column1);
		return (M)this;
	}
	
	public java.lang.String getColumn1() {
		return getStr("column1");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setOutLink(java.lang.String outLink) {
		set("out_link", outLink);
		return (M)this;
	}
	
	public java.lang.String getOutLink() {
		return getStr("out_link");
	}

	public M setPicture(java.lang.String picture) {
		set("picture", picture);
		return (M)this;
	}
	
	public java.lang.String getPicture() {
		return getStr("picture");
	}

	public M setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
		return (M)this;
	}
	
	public java.util.Date getUpdatetime() {
		return get("updatetime");
	}

	public M setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
		return (M)this;
	}
	
	public java.util.Date getCreatetime() {
		return get("createtime");
	}

	public M setClickcount(java.lang.Integer clickcount) {
		set("clickcount", clickcount);
		return (M)this;
	}
	
	public java.lang.Integer getClickcount() {
		return getInt("clickcount");
	}

	public M setCommentcount(java.lang.Integer commentcount) {
		set("commentcount", commentcount);
		return (M)this;
	}
	
	public java.lang.Integer getCommentcount() {
		return getInt("commentcount");
	}

	public M setThumbnail(java.lang.String thumbnail) {
		set("thumbnail", thumbnail);
		return (M)this;
	}
	
	public java.lang.String getThumbnail() {
		return getStr("thumbnail");
	}

	public M setLanmuId(java.lang.Integer lanmuId) {
		set("lanmu_id", lanmuId);
		return (M)this;
	}
	
	public java.lang.Integer getLanmuId() {
		return getInt("lanmu_id");
	}

	public M setSortNum(java.lang.Integer sortNum) {
		set("sort_num", sortNum);
		return (M)this;
	}
	
	public java.lang.Integer getSortNum() {
		return getInt("sort_num");
	}

	public M setStatus(java.lang.Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public M setGzDelete(java.lang.Integer gzDelete) {
		set("gzDelete", gzDelete);
		return (M)this;
	}
	
	public java.lang.Integer getGzDelete() {
		return getInt("gzDelete");
	}

	public M setCheckState(java.lang.Integer checkState) {
		set("check_state", checkState);
		return (M)this;
	}
	
	public java.lang.Integer getCheckState() {
		return getInt("check_state");
	}

}
